version: '3.3'

services:
  app:
    build: .
    container_name: app-example
    network_mode: host
    ports: []
    command: bash -c "uvicorn app.main:app"
    env_file:
      - .env
    volumes:
      - ./fastapi_app.db:/app/fastapi_app.db:delegated

